export const treeAfterToggleFavorites = {
  key: "0",
  label: "root",
  to: "/",
  icon: "pi pi-home",
  items: [
    {
      key: "1",
      label: "Kitchen",
      favorites: true,
      icon: "https://media.istockphoto.com/photos/blue-sky-and-white-clouds-background-picture-id825778252?b=1&k=20&m=825778252&s=612x612&w=0&h=C2j1HeXd5swrFsvrBqN9GIUmewXPSERRg9quVii3prM=",
      to: "/section/1",
      items: [
        {
          key: "1_1",
          label: "Store",
          to: "/section/1_1",
          items: [
            {
              key: "1_1_1",
              label: "Fork",
              favorites: true,
              description: "this is a fork",
              tags: [{ name: "Tag1", favorite: false }],
              quantity: 24,
              to: `/item/1_1_1`,
            },
            {
              key: "1_1_2",
              label: "Spoon",
              description: "this is a spoon",
              tags: [{ name: "Tag2", favorite: false }],
              quantity: 14,
              to: "/item/1_1_2",
            },
          ],
        },
      ],
    },
    {
      key: "2",
      label: "Garage",
      favorites: false,
      to: "/section/2",
      items: [
        {
          key: "2_1",
          label: "Toolbox",
          favorites: false,
          to: "/section/2_1",
          items: [
            {
              key: "2_1_1",
              label: "Hummer",
              favorites: true,
              description: "this is a Hummer",
              tags: [{ name: "Tag3", favorite: false }],
              quantity: 1,
              to: "/item/2_1_1",
            },
            {
              key: "2_1_2",
              label: "Wrench 1",
              favorites: false,
              description: "this is a Wrench",
              tags: [{ name: "Tag4", favorite: false }],
              quantity: 1,
              to: `/item/2_1_2`,
            },
            {
              key: "2_1_3",
              label: "Flat screwdriwer",
              favorites: false,
              description: "this is a screwdriwer",
              tags: [{ name: "Tag1", favorite: false }],
              quantity: 4,
              to: "/item/2_1_3",
            },
          ],
        },
        {
          key: "2_2",
          label: "Case",
          favorites: false,
          to: "/section/2_2",
          items: [
            {
              key: "2_2_1",
              label: "Nuts",
              favorites: true,
              description: "this is Nuts",
              tags: [{ name: "Tag2", favorite: false }],
              quantity: 54,
              to: "/item/2_2_1",
            },
            {
              key: "2_2_2",
              label: "Bolts",
              favorites: false,
              description: "this is Bolts",
              tags: [{ name: "Tag3", favorite: false }],
              quantity: 31,
              to: `/item/2_2_2`,
            },
          ],
        },
      ],
    },
    {
      key: "3",
      label: "Empty Node",
      to: "/section/3",
      items: [],
    },
  ],
};
